### ISSUE TITLE
Error when opening GUI Title and Status from Eclipse UI

### ISSUE THREAD

**Issue by MDJoerg** [fidley/ADT-Classic-Outline-Backend#10]
Hi Lukas,

I have found an error in your classic outline extension for eclipse. While opening GUI Title or GUI Status an error occurs in the SAPGUI embedded view (see screenshots). 

![grafik](https://user-images.githubusercontent.com/41207683/145979134-37410a9c-1ebe-48bb-9672-e78c14cb4191.png)

![grafik](https://user-images.githubusercontent.com/41207683/145979043-341a9d87-6edd-4389-b99a-99eed6f03d38.png)

I have checked this against standard ADT functionality. Opening of the same objects was possible.

![grafik](https://user-images.githubusercontent.com/41207683/145979683-bcd13155-f08c-40fa-becf-e56d3f17eeb3.png)

Opening a screen via Classic Outline will produce a dump.

![grafik](https://user-images.githubusercontent.com/41207683/145979889-e4a1db0a-fa2e-4ab1-b7e8-1711ece69e45.png)

The same in ADT standard was OK.

In this case them program was implemented in partner namespace. This could be the reason?

Thank you for the greate extensions and for your time invested in!

Best regards
Joerg

**Comment by fidley** [comment]
Sorry for so late answer. I have really limited time now and I''ve missed it.
You may be right, the namespace can be the problem, but I will investigate this :)

**Comment by fidley** [comment]
I've tested it. Seems the issue happens when the namespace is used. The calculater URI to open the object is correct and same as the ones create by SAP. But somehow during opening of the ADT link it is getting wrongly interpreted and instead of replacing %20 into spaces, it is used as a part of the program name. This cause this silly error.
I need to speak to some SAP colleagues :)

**Comment by fidley** [comment]
I am very close on the way to solve this. The issue as said is URI handling and I think I've got it. Additionally, as function groups/FM that having namespaces needs to be handled correctly. I'm working on it using the /aif/contact_list program and /aif/ext_contact_up FG

**Comment by fidley** [comment]
Please update Frontend & Backend components. Should work with the latest changes correctly.

**Comment by MDJoerg** [comment]
Thank You!
