### ISSUE TITLE
Dump when opening screens 

### ISSUE THREAD

**Issue by JulesGei1337** [fidley/ADT-Classic-Outline-Backend#15]
It dumps after double-clicking on any Screen in any programm. See below:

![image](https://user-images.githubusercontent.com/108661194/177119870-ccaf26d4-a49e-4717-bf7f-c0f9a94fde0f.png)

This is for standard 1000er Screen also as for own Screens. This is the dump protocoll
![image](https://user-images.githubusercontent.com/108661194/177121532-ba51cb7f-7f3d-45de-84ed-25d36b35d938.png)
![image](https://user-images.githubusercontent.com/108661194/177121560-c575f2b9-c033-4016-a87e-7cf712287761.png)

Seems like the Dynpronumber shouldn´t be 0%20 but 1000 :)
If i change it manually in the debugger in do not dump anymore, but also no screen is displayed

![image](https://user-images.githubusercontent.com/108661194/177121716-7731c256-fd4f-490e-a2a8-beee9426912c.png)

**Comment by fidley** [comment]
We had something similar before when the custom namespaces were used (#10) but this was solved. Do you have the latest backend version installed?

**Comment by JulesGei1337** [comment]
I have the latest backend version, i deleted it and pulled it again, but does still not work.

![image](https://user-images.githubusercontent.com/108661194/177166696-5b7c938e-3781-4dae-8f57-ed963cbcc31b.png)

GUI Status and GUI Title are working, its only dumping at the screens

What I forgot to say at the beginnging:
Thank you for your effort and this great plugin!

**Comment by fidley** [comment]
You're welcome ;)

But in order to solve the issue on your installation I would need more details. Do you use custom namespace or not? If not then maybe I'll ask you for more details :)

**Comment by fidley** [comment]
Ok. I found the answer myself. For namespaces screen navigation does not work. I will check that.

![image](https://user-images.githubusercontent.com/7912195/177170076-4ba93715-dac6-43ba-830d-2b9db02d80af.png)

**Comment by JulesGei1337** [comment]
I installed it in a local package in $TMP of my user. It will not be transported, so no custom namespace. Local packages have to begin with $ but not more ;)

What do you need?

**Comment by fidley** [comment]
Please update the plugin from this url [](https://raw.githubusercontent.com/fidley/ADTPluginsUpdateSite/master/Update Site/).
If it will be working for you, then I will publish it on official update site.

**Comment by JulesGei1337** [comment]
I tried, but i think the link is broken :) Is it:
https://raw.githubusercontent.com/fidley/ADTPluginsUpdateSite/master/Update/Site/ ?
but it worked neither

**Comment by fidley** [comment]
https://raw.githubusercontent.com/fidley/ADTPluginsUpdateSite/master/Update Site/ with space inside
![image](https://user-images.githubusercontent.com/7912195/177268225-fea6e035-205c-432c-b7bc-6375dff6bcb6.png)

**Comment by JulesGei1337** [comment]
I would say: it works on my machine
![image](https://user-images.githubusercontent.com/108661194/177275773-95548883-88ae-47cd-84c9-121c29d44f25.png)

Thank u a lot :) 👍
